---
- name: Win ping
  hosts: 10.27.5.129
  gather_facts: no

  tasks:
      - command: useradd test
   #  - command: ansible -m ping 10.27.5.129
   #    register: hello
   # - debug: msg="{hello.stdout}"
