---
- name: Win ping
  hosts: all
  gather_facts: no

  tasks:
    - win_shell: $ping = New-Object System.Net.Networkinformation.Ping 1..254 | % { $ping.send(“172.18.69.$_”) | select address, status }
    
