---
- name: Win ping
  hosts: 172.18.69.53
  gather_facts: no

  tasks:
      - command: useradd test
        delegate_to: "10.27.5.129"
   #  - command: ansible -m ping 10.27.5.129
   #    register: hello
   # - debug: msg="{hello.stdout}"
