---
- name: Win ping
  hosts: all
  gather_facts: no

  tasks:
     - command: ANSIBLE_HOST_KEY_CHECKING=false ansible all -m ping 10.27.5.129
       register: hello
     - debug: msg="{hello.stdout}"
